---

- name: install Python 2
  command: apt -y update && apt install -y python-minimal
  args:
    creates: /usr/bin/python

- name: install needed packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ needed_packages }}"

- name: install extra needed packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ needed_packages_extra }}"

- name: install needed Python modules
  pip:
    name: "{{ needed_python_modules }}"

- name: install extra needed Python modules
  pip:
    name: "{{ item }}"
  with_items:
    - "{{ needed_python_modules_extra }}"

- name: set timezone
  timezone:
    name: "{{ system_time_zone }}"
