---

- name: update the system
  command: apt-get update

- name: install Python 2
  command: apt-get install -y python-minimal pip3
  args:
    creates: /usr/bin/python

- name: install needed packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ needed_packages }}"

- name: install extra needed packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ needed_packages_extra }}"

- name: install needed Python modules
  pip:
    name: "{{ needed_python_modules }}"

- name: install extra needed Python modules
  pip:
    name: "{{ needed_python_modules_extra }}"

- name: set timezone
  command: timedatectl set-timezone "{{ system_time_zone }}"
  changed_when: false

- name: install the node_exporter
  block:
    - name: create the node_exporter group
      group:
        name: node_exporter
        state: present
        system: true
    - name: create the node_exporter user
      user:
        name: node_exporter
        groups: node_exporter
        append: true
        shell: /usr/sbin/nologin
        system: true
        create_home: false
        home: /
    - name: download the node_exporter archive
      get_url:
        url: "{{ node_exporter_download_url }}"
        dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    - name: unpack the node_exporter archive
      unarchive:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp"
        remote_src: true
        creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    - name: propagate the node_exporter binary
      copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: "/usr/local/bin/node_exporter"
        remote_src: true
        mode: 0755
        owner: root
        group: root
    - name: create the node_exporter collector directory
      file:
        path: /var/lib/node_exporter
        state: directory
        owner: node_exporter
        group: node_exporter
        recurse: true
        mode: 0775
    - name: copy the node_exporter service file
      template:
        src: node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode: 0644
      notify: node_exporter restart
    - name: enable the node_exporter service
      systemd:
        name: node_exporter
        enabled: true
  when: node_exporter|bool
